### ISSUE TITLE
Suggestion : Make it compatible with Carousel Combat Tracker

### ISSUE THREAD

**Issue by federicoacker** [operation404/boneyard-turn-timer#3]
Hi, loving the timer module. Being able to set custom timer for each player has really improved the overall time management during our fights. I was thinking though that it would be cool if there was a way for it to be integrated into carousel combat tracker, to be able to see the timer in the carousel if the combat tracker is closed

**Comment by operation404** [comment]
I haven't used that module before, but I'll take a look at it and see if it's something that could be reasonably added.

**Comment by federicoacker** [comment]
Nice xD please let me know if you find a way to make it work, if it's too much trouble but you have an idea on how it'd work I can try and make a fork to implement compatibility if you're too busy ^^

**Comment by operation404** [comment]
You're free to fork as you see fit, but it's also something I'll likely work on within the week. One of the planned future features for this module was a popout timer, something like a small window with just a timer and a button to end your turn. Would that suffice for your use case, or are you looking for something more integrated with that specific module?

**Comment by federicoacker** [comment]
Oh that's perfect thank you very much ^^

**Comment by operation404** [comment]
Sorry this took as long as it did, I had a bit of complications but the popout timer should now be implemented in release 2.1.0 and hopefully fulfills the needs you had. Let me know if you encounter any issues with it or have suggestions for improvements.
